<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>DemoApp.Legacy.Infrastructure</RootNamespace>
    <AssemblyName>DemoApp.Legacy.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
