<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>DemoApp.Abstractions</RootNamespace>
    <AssemblyName>DemoApp.Abstractions</AssemblyName>
  </PropertyGroup>
</Project>
