<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>DemoApp.Legacy.ApiHost</RootNamespace>
    <AssemblyName>DemoApp.Legacy.ApiHost</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.OwinSelfHost" Version="5.2.9" />
    <PackageReference Include="Microsoft.Owin.Host.HttpListener" Version="4.2.2" />
    <PackageReference Include="Microsoft.Owin.Hosting" Version="4.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DemoApp.Abstractions\DemoApp.Abstractions.csproj" />
    <ProjectReference Include="..\DemoApp.Legacy.ClassicLib\DemoApp.Legacy.ClassicLib.csproj" />
    <ProjectReference Include="..\DemoApp.Legacy.Data\DemoApp.Legacy.Data.csproj" />
    <ProjectReference Include="..\DemoApp.Legacy.Infrastructure\DemoApp.Legacy.Infrastructure.csproj" />
    <ProjectReference Include="..\DemoApp.Shared\DemoApp.Shared.csproj" />
  </ItemGroup>
</Project>
