<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>DemoApp.Shared</RootNamespace>
    <AssemblyName>DemoApp.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DemoApp.Abstractions\DemoApp.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
